import { NextRequest } from "next/server";
import { fail, guard, isResponse } from "@/lib/api";
import { toCsv } from "@/lib/csv";
import { store } from "@/lib/store";
import { traceVehicle } from "@/lib/trace";

/** Route report export for an investigation file (Flow C step 5). */
export async function GET(req: NextRequest) {
  const g = await guard("report.export");
  if (isResponse(g)) return g;
  const q = req.nextUrl.searchParams;
  const plate = q.get("plate")?.trim();
  if (!plate) return fail(400, "plate is required");

  const result = traceVehicle({
    plate,
    fuzzy: q.get("fuzzy") === "true",
    from: q.get("from"),
    to: q.get("to"),
    deptId: g.scope,
  });

  const rows = result.hops.map((h, i) => ({
    sequence: i + 1,
    timestamp_ist: new Date(h.timestamp).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" }),
    timestamp_utc: h.timestamp,
    plate_read: h.plateRead,
    match_type: h.fuzzy ? "PROBABLE (OCR variant)" : "EXACT",
    confidence: h.confidence,
    camera_id: h.cameraId,
    camera_name: h.cameraName,
    site: h.site,
    district: h.district,
    department: h.deptName,
    latitude: h.lat,
    longitude: h.lng,
    direction: h.direction ?? "",
    speed_kph: h.speedKph ?? "",
    leg_distance_km: h.leg?.km ?? "",
    leg_minutes: h.leg?.minutes ?? "",
    leg_implied_kph: h.leg?.impliedKph ?? "",
    leg_plausible: h.leg ? (h.leg.plausible ? "YES" : "NO") : "",
    leg_note: h.leg?.reason ?? "",
    evidence_frame: h.frameRef,
  }));

  store.audit({
    actor: g.session.username,
    role: g.session.role,
    action: "report.trace_export",
    entity: "Vehicle",
    entityId: result.query,
    detail: `Route report exported: ${result.summary.hits} hits, ${result.summary.totalKm} km, ${result.summary.flaggedLegs} flagged legs`,
  });

  const header = [
    `# Sentinel IVMAP — Vehicle Movement Report`,
    `# Vehicle,${result.query}`,
    `# Generated,${new Date().toISOString()}`,
    `# Generated by,${g.session.name} (${g.session.role})`,
    `# Hits,${result.summary.hits}`,
    `# Cameras,${result.summary.cameras}`,
    `# Departments,${result.summary.departments}`,
    `# Districts,"${result.summary.districts.join(", ")}"`,
    `# Route distance km,${result.summary.totalKm}`,
    `# Window minutes,${result.summary.durationMinutes}`,
    `# Flagged legs,${result.summary.flaggedLegs}`,
    `# Watchlisted,${result.summary.watchlisted ? result.summary.watchlistCategory : "no"}`,
    "",
  ].join("\r\n");

  const filename = `sentinel-trace-${result.query}-${Date.now()}.csv`;
  return new Response(header + toCsv(rows), {
    headers: {
      "content-type": "text/csv; charset=utf-8",
      "content-disposition": `attachment; filename="${filename}"`,
    },
  });
}
